[package]
name = "tidy"
version = "0.1.0"
edition = "2021"
autobins = false

[dependencies]
cargo_metadata = "0.14"
regex = "1"
lazy_static = "1"
walkdir = "2"

[[bin]]
name = "rust-tidy"
path = "src/main.rs"
