[book]
src = "src"
title = "The rustdoc book"

[output.html]
git-repository-url = "https://github.com/rust-lang/rust/tree/master/src/doc/rustdoc"

[output.html.redirect]
"/the-doc-attribute.html" = "write-documentation/the-doc-attribute.html"
"/documentation-tests.html" = "write-documentation/documentation-tests.html"
