[package]
name = "rustc_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
annotate-snippets = "0.9"
fluent-bundle = "0.15.2"
fluent-syntax = "0.11"
synstructure = "0.12.1"
syn = { version = "1", features = ["full"] }
proc-macro2 = "1"
quote = "1"
unic-langid = { version = "0.9.0", features = ["macros"] }
