[package]
name = "rustc_serialize"
version = "0.0.0"
edition = "2021"

[dependencies]
indexmap = "1.9.1"
smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
thin-vec = "0.2.8"

[dev-dependencies]
rustc_macros = { path = "../rustc_macros" }
