[package]
name = "ide-completion"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.57"

[lib]
doctest = false

[dependencies]
cov-mark = "2.0.0-pre.1"
itertools = "0.10.5"

once_cell = "1.15.0"
smallvec = "1.10.0"

stdx = { path = "../stdx", version = "0.0.0" }
syntax = { path = "../syntax", version = "0.0.0" }
text-edit = { path = "../text-edit", version = "0.0.0" }
base-db = { path = "../base-db", version = "0.0.0" }
ide-db = { path = "../ide-db", version = "0.0.0" }
profile = { path = "../profile", version = "0.0.0" }

# completions crate should depend only on the top-level `hir` package. if you need
# something from some `hir-xxx` subpackage, reexport the API via `hir`.
hir = { path = "../hir", version = "0.0.0" }

[dev-dependencies]
expect-test = "1.4.0"

test-utils = { path = "../test-utils" }
