#! /usr/bin/env bash

set -e

VERSION="v0.1"
#readonly DOCKER_USER="${USER:-root}"
readonly DOCKER_USER="jjf"
readonly PWD=`pwd`
docker run -it -v ${PWD}:/home/${DOCKER_USER}/Fuzzing-Target-Generator --rm fuzz-target-generator:$VERSION
