#! /usr/bin/env bash
set -e

cd "$(cd "$(dirname "$0")" && pwd)"
readonly VERSION="v0.1"
readonly DOCKER_IMAGE_NAME="rumono"
readonly DOCKER_UID="${UID:-0}"
readonly DOCKER_GID="$(id -g)"
# We use default user here, since our code hardcode username
readonly DOCKER_USER="rumono"
# readonly DOCKER_USER="${USER:-root}"

docker image build \
    --cache-from="$DOCKER_IMAGE_NAME:$VERSION" \
    -t $DOCKER_IMAGE_NAME:$VERSION \
    --build-arg=USERNAME="$DOCKER_USER" \
    --build-arg=USER_UID="$DOCKER_UID" \
    --build-arg=USER_GID="$DOCKER_GID" \
    --build-arg=UBUNTU_VERSION="20.04" \
    . 1>&2