[package]
name = "xtask"
version = "0.1.0"
publish = false
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.57"

[dependencies]
anyhow = "1.0.62"
flate2 = "1.0.24"
write-json = "0.1.2"
xshell = "0.2.2"
xflags = "0.3.0"
# Avoid adding more dependencies to this crate
