[package]
name = "project-model"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.57"

[lib]
doctest = false

[dependencies]
tracing = "0.1.35"
rustc-hash = "1.1.0"
cargo_metadata = "0.15.0"
semver = "1.0.14"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.86"
anyhow = "1.0.62"
la-arena = { version = "0.3.0", path = "../../lib/la-arena" }

cfg = { path = "../cfg", version = "0.0.0" }
base-db = { path = "../base-db", version = "0.0.0" }
toolchain = { path = "../toolchain", version = "0.0.0" }
paths = { path = "../paths", version = "0.0.0" }
stdx = { path = "../stdx", version = "0.0.0" }
profile = { path = "../profile", version = "0.0.0" }

[dev-dependencies]
expect-test = "1.4.0"
