
[package]
name = "syntax-fuzz"
version = "0.0.1"
publish = false
edition = "2021"
rust-version = "1.57"

[package.metadata]
cargo-fuzz = true

[dependencies]
syntax = { path = "..", version = "0.0.0" }
text_edit = { path = "../../text_edit", version = "0.0.0" }
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "parser"
path = "fuzz_targets/parser.rs"

[[bin]]
name = "reparse"
path = "fuzz_targets/reparse.rs"
