[package]
name = "rustc-workspace-hack"
version = "1.0.0"
license = 'MIT OR Apache-2.0'
description = """
Hack for the compiler's own build system
"""
edition = "2021"

[lib]
path = "lib.rs"

# For documentation about what this is and why in the world these dependencies
# are appearing, see `README.md`.

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3"
features = [
  "accctrl",
  "aclapi",
  "basetsd",
  "cfg",
  "consoleapi",
  "errhandlingapi",
  "evntrace",
  "fibersapi",
  "handleapi",
  "in6addr",
  "inaddr",
  "ioapiset",
  "jobapi",
  "jobapi2",
  "knownfolders",
  "libloaderapi",
  "lmcons",
  "memoryapi",
  "minschannel",
  "minwinbase",
  "mstcpip",
  "mswsock",
  "namedpipeapi",
  "ntdef",
  "ntsecapi",
  "ntstatus",
  "objbase",
  "processenv",
  "processthreadsapi",
  "profileapi",
  "psapi",
  "schannel",
  "securitybaseapi",
  "shellapi",
  "shlobj",
  "sspi",
  "synchapi",
  "sysinfoapi",
  "threadpoollegacyapiset",
  "timezoneapi",
  "userenv",
  "winbase",
  "wincon",
  "wincrypt",
  "windef",
  "winioctl",
  "winnt",
  "winreg",
  "winsock2",
  "winuser",
  "ws2def",
  "ws2ipdef",
  "ws2tcpip",
]

[dependencies]
bstr = { version = "0.2.17", features = ["default"] }
clap = { version = "3.1.1", features = ["derive", "clap_derive"]}
curl-sys = { version = "0.4.13", features = ["http2", "libnghttp2-sys"], optional = true }
# Ensure default features of libz-sys, which are disabled in some scenarios.
libz-sys = { version = "1.1.2" }
# Ensure default features of regex, which are disabled in some scenarios.
regex = { version = "1.5.6" }
serde_json = { version = "1.0.31", features = ["raw_value", "unbounded_depth"] }
syn = { version = "1", features = ['full', 'visit'] }
url = { version = "2.0", features = ['serde'] }

[target.'cfg(not(windows))'.dependencies]
openssl = { version = "0.10.35", optional = true }

[features]
all-static = ['openssl/vendored', 'curl-sys/static-curl', 'curl-sys/force-system-lib-on-osx']
