#! /usr/bin/env bash

set -e

# build this toolchain and set as the default toolchain
# This is also run when we modify the source codes and recompile
USER_NAME="${USER:-root}"
RUMONO_DIR=/home/${USER_NAME}/RuMono
cd ${RUMONO_DIR}
python3 ./x.py build --stage 2 src/tools/cargo src/tools/rustfmt src/tools/clippy 
rustup toolchain link stage2 ${RUMONO_DIR}/build/x86*/stage2 && rustup default stage2 