#! /usr/bin/env bash
set -e

# install fuzzing scripts
TMP_DIR=${HOME}
cd ${TMP_DIR}
if [ ! -d "${TMP_DIR}/Fuzzing-Scripts" ]; then
   git clone https://github.com/Artisan-Lab/Fuzzing-Scripts
fi
cd Fuzzing-Scripts
cargo install --path afl_scripts
cargo install --path find_literal
cd ${TMP_DIR} && rm -rf Fuzzing-Scripts