[package]
name = "ide-diagnostics"
version = "0.0.0"
description = "TBD"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.57"

[lib]
doctest = false

[dependencies]
cov-mark = "2.0.0-pre.1"
either = "1.7.0"
itertools = "0.10.5"
serde_json = "1.0.86"

profile = { path = "../profile", version = "0.0.0" }
stdx = { path = "../stdx", version = "0.0.0" }
syntax = { path = "../syntax", version = "0.0.0" }
text-edit = { path = "../text-edit", version = "0.0.0" }
cfg = { path = "../cfg", version = "0.0.0" }
hir = { path = "../hir", version = "0.0.0" }
ide-db = { path = "../ide-db", version = "0.0.0" }

[dev-dependencies]
expect-test = "1.4.0"

test-utils = { path = "../test-utils" }
sourcegen = { path = "../sourcegen" }

[features]
in-rust-tree = []
