#! /usr/bin/env bash

set -e

# copy Fuzzing Scripts from host to container
# git clone may sometimes fail, so we copy from host

CONTAINER_ID="68debb479a3f"
DOCKER_USER="jjf"
docker cp ${HOME}/Fuzzing-Scripts ${CONTAINER_ID}:/home/${DOCKER_USER}